name: Java CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  Build:
    strategy:
      matrix:
        jdkversion: [11]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdkversion }}
        cache: 'maven'
    - name: 使用Maven构建
      run: mvn -V -B clean package --file pom.xml